# Mod
mod_id = trashslot
mod_name = TrashSlot
mod_main=TrashSlot
description=Adds a trash slot to the inventory screen that allows deletion of unwanted items.
version = 21.11.3
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/mc/trashslot
sources=https://github.com/TwelveIterationMods/TrashSlot
issues=https://github.com/TwelveIterationMods/TrashSlot/issues
discord = https://discord.gg/VAfZ2Nau6j
license=All Rights Reserved

# Publishing
curseforge_project_id = 235577
curseforge_environments = Client,Server
modrinth_project_id = vRYk0bv7
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Minecraft
pack_format_number = 64
java_version = 21

# NeoForge
neoforge_snapshot_url = 

# Dependencies
jei_minecraft_version=1.19.2
jei_version=11.4.0.288
rei_version=10.0.581
modmenu_version=9.0.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_author = BlayTheNinth
credits = BlayTheNinth
