modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="trashslot"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="trashslot.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "trashslot.mixins.json"
[[mixins]]
config = "trashslot.neoforge.mixins.json"
[[dependencies.trashslot]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.trashslot]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.trashslot]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
